import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <ul className="flex w-full justify-center text-white gap-2 mt-2 mb-2">
            <li
              className={`    
          hover:bg-neutral-700 
          hover:cursor-pointer
            transition-all
            ease-in-out
            duration-500
            p-2
            rounded-md
            `}
            >
              <Link href="/"> Home</Link>
            </li>
            <li
              className={`    
          hover:bg-neutral-700 
            hover:cursor-pointer
            transition-all
            ease-in-out
            duration-500
            p-2
            rounded-md
            `}
            >
              <Link href="/about"> About project</Link>
            </li>
          </ul>
        </nav>
        {children}
        <footer className="text-center p-2 font-semibold text-white text-sm">
          Made in 2023
        </footer>
      </body>
    </html>
  );
}
